language: python

os:
  - linux

python:
  - 3.6

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - ./install.sh
  - source _virtualenv/bin/activate
  - pip install -r requirements-dev.txt

script:
  - ./test.sh

after_success:
  - codecov

notifications:
  email: false
